### ISSUE TITLE
Broken model hashes

### ISSUE THREAD

**Issue by ghost** [MichiyamaKaren/ultimatevocalremover-webui#3]
I think this is fixable if model_data.json gets updated but the models fail due undefined things in a .py (i don't remember which but i think it was UVR_interface.py)

Example
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 217, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1553, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1191, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 659, in wrapper
    response = f(*args, **kwargs)
  File "/content/ultimatevocalremover-colab/webUI.py", line 123, in process
    seperator = uvr.process(
  File "/content/ultimatevocalremover-colab/UVR_interface.py", line 684, in process
    seperator = SeperateMDX(model, process_data)
  File "/content/ultimatevocalremover-colab/separate.py", line 76, in __init__
    self.overlap = model_data.overlap
AttributeError: 'ModelData' object has no attribute 'overlap'
```

**Comment by Juranik** [comment]
Bro it still working?

**Comment by Aldair502** [comment]
> Bro it still working?

i mean i could fix it but im learning to use dvorak so i currently can't
