### ISSUE TITLE
Pls, help...

### ISSUE THREAD

**Issue by Juranik** [MichiyamaKaren/ultimatevocalremover-webui#6]
```
`2023-11-12 16:18:27,574 - UVR BEGIN
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
2023-11-12 16:18:53,472 - HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
2023-11-12 16:18:53,526 - Task exception was never retrieved
future: <Task finished name='i3cszgik4t_3' coro=<Queue.process_events() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py:329> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 343, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 303, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data
2023-11-12 16:18:53,530 - HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
2023-11-12 16:18:53,589 - Task exception was never retrieved
future: <Task finished name='i3cszgik4t_2' coro=<Queue.process_events() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py:329> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 343, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 303, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data
2023-11-12 16:18:53,592 - HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
2023-11-12 16:18:53,653 - Task exception was never retrieved
future: <Task finished name='i3cszgik4t_1' coro=<Queue.process_events() done, defined at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py:329> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 343, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 303, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data
2023-11-12 16:18:53,656 - HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"`
```

What this error?

**Comment by Aldair502** [comment]
maybe it's broken on 3.10 ldk or that model is not supported

**Comment by Juranik** [comment]
> maybe it's broken on 3.10 ldk or that model is not supported

Noice, btw I fixed this... Ima just puted model mdx net and select it, it worked witohut github/dora xD, but pls bro can u slightly change the api structure so that there is also an input_audio and output_folder type parameter

**Comment by Aldair502** [comment]
> > maybe it's broken on 3.10 ldk or that model is not supported
> 
> Noice, btw I fixed this... Ima just puted model mdx net and select it, it worked witohut github/dora xD, but pls bro can u slightly change the api structure so that there is also an input_audio and output_folder type parameter

im not the mantainer but ok (anyways i think i should rewrite this)

**Comment by Juranik** [comment]
> > > maybe it's broken on 3.10 ldk or that model is not supported
> > 
> > 
> > Noice, btw I fixed this... Ima just puted model mdx net and select it, it worked witohut github/dora xD, but pls bro can u slightly change the api structure so that there is also an input_audio and output_folder type parameter
> 
> im not the mantainer but ok (anyways i think i should rewrite this)

:)......

**Comment by Aldair502** [comment]
> > maybe it's broken on 3.10 ldk or that model is not supported
> 
> Noice, btw I fixed this... Ima just puted model mdx net and select it, it worked witohut github/dora xD, but pls bro can u slightly change the api structure so that there is also an input_audio and output_folder type parameter

im going to de this on saturday

**Comment by Juranik** [comment]
> > > maybe it's broken on 3.10 ldk or that model is not supported
> > 
> > 
> > Noice, btw I fixed this... Ima just puted model mdx net and select it, it worked witohut github/dora xD, but pls bro can u slightly change the api structure so that there is also an input_audio and output_folder type parameter
> 
> im going to de this on saturday

Delete???!!!!
